/apps_actuator_node:
  ros__parameters:
    generic:
      spi_device: "/dev/spidev1.0"
      speed: 50000
      WCET: 5000000 # ms
      period: 10000000 # 10ms
      deadline: 10000000
    topic:
      appsTopic: "/apps/percentage"