/canbus_bridge_node:
  ros__parameters:
    generic:
      interface: vcan0
      bitrate: 1000000
      debug: true
      WCET: 5000000 # ms
      period: 10000000 # 10ms
      deadline: 10000000
      max_msgs: 5
    topic:
      canTxTopic: "/canbus/tx/msg"
      canRxTopic: "/canbus/rx/msg"